# Generated by Django 5.0 on 2023-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0002_byte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byte',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
