# Generated by Django 5.0 on 2023-12-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0003_alter_byte_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='byte',
            old_name='desc',
            new_name='description',
        ),
    ]
