# Generated by Django 5.0 on 2023-12-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0004_rename_desc_byte_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='byte',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('purchased', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bytes.profile')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('byte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bytes.byte')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bytes.order')),
            ],
        ),
    ]
