# Generated by Django 5.0 on 2023-12-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0006_remove_order_profile_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
