# Generated by Django 5.0 on 2023-12-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0007_alter_order_order_date_alter_order_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('byte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bytes.byte')),
            ],
        ),
    ]
